stages:
  - build
  - integration-test
  - deploy

gradle-build:
  image: gradle:6.7.1-jdk11
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean build
  artifacts:
    paths:
      - build/libs/*.jar
    reports:
      junit: build/test-results/test/**/TEST-*.xml

  cache:
    key: gradle-cache
    paths:
      - .gradle/caches

gradle-integration-test:
  image: gradle:6.7.1-jdk11
  stage: integration-test
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - gradle clean integrationTest
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: gradle-cache
    paths:
      - .gradle/caches

heroku-deploy:
  image: docker:stable
  stage: deploy
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build --build-arg JAR_FILE=`ls build/libs/*.jar | head -1` --build-arg DB_URI=${PET_CLINIC_DB_URI} --build-arg DB_USER=${PET_CLINIC_DB_USER} --build-arg DB_PASSWORD=${PET_CLINIC_DB_PASSWORD} --tag registry.heroku.com/$PET_CLINIC_APP_NAME/web .
    - docker push registry.heroku.com/$PET_CLINIC_APP_NAME/web
    - chmod +x ./release-docker-in-heroku.sh
    - ./release-docker-in-heroku.sh $PET_CLINIC_APP_NAME $HEROKU_API_KEY